package menu_odevi;

public enum ECorba {
	MERCIMEK_CORBASI,
	TARHANA_CORBASI,
	YAYLA_CORBASI,
	ISKEMBE_CORBASI,
	EZOGELIN_CORBASI,
	DOMATES_CORBASI,
	SEHRIYE_CORBASI,
	DUGUN_CORBASI,
	PACA_CORBASI,
	SEBZE_CORBASI,
	TAVUKLU_CORBA;
}
