insert into tblurun (ad, fiyat) values ('Cocoa Powder - Dutched', 81);
insert into tblurun (ad, fiyat) values ('Buttons', 283);
insert into tblurun (ad, fiyat) values ('Wine - Merlot Vina Carmen', 640);
insert into tblurun (ad, fiyat) values ('Pimento - Canned', 208);
insert into tblurun (ad, fiyat) values ('Ecolab - Solid Fusion', 385);
insert into tblurun (ad, fiyat) values ('Foam Dinner Plate', 36);
insert into tblurun (ad, fiyat) values ('Vodka - Lemon, Absolut', 569);
insert into tblurun (ad, fiyat) values ('Longos - Grilled Chicken With', 564);
insert into tblurun (ad, fiyat) values ('Milk - Buttermilk', 245);
insert into tblurun (ad, fiyat) values ('Squash - Pattypan, Yellow', 396);
insert into tblurun (ad, fiyat) values ('Sobe - Tropical Energy', 515);
insert into tblurun (ad, fiyat) values ('Sprouts - Brussel', 16);
insert into tblurun (ad, fiyat) values ('Mushrooms - Honey', 387);
insert into tblurun (ad, fiyat) values ('Wine - Carmenere Casillero Del', 394);
insert into tblurun (ad, fiyat) values ('Longos - Chicken Caeser Salad', 217);
insert into tblurun (ad, fiyat) values ('Shrimp - 31/40', 552);
insert into tblurun (ad, fiyat) values ('Coffee - Dark Roast', 476);
insert into tblurun (ad, fiyat) values ('Apple - Macintosh', 269);
insert into tblurun (ad, fiyat) values ('Parsley Italian - Fresh', 513);
insert into tblurun (ad, fiyat) values ('Couscous', 477);
insert into tblurun (ad, fiyat) values ('Icecream - Dibs', 194);
insert into tblurun (ad, fiyat) values ('Zucchini - Green', 16);
insert into tblurun (ad, fiyat) values ('Lid - 10,12,16 Oz', 622);
insert into tblurun (ad, fiyat) values ('Lamb - Leg, Bone In', 506);
insert into tblurun (ad, fiyat) values ('Butter - Unsalted', 118);
insert into tblurun (ad, fiyat) values ('Ecolab - Orange Frc, Cleaner', 406);
insert into tblurun (ad, fiyat) values ('Marjoram - Dried, Rubbed', 29);
insert into tblurun (ad, fiyat) values ('Chambord Royal', 29);
insert into tblurun (ad, fiyat) values ('Tart Shells - Savory, 3', 64);
insert into tblurun (ad, fiyat) values ('Bread - Hamburger Buns', 605);
insert into tblurun (ad, fiyat) values ('Beer - Pilsner Urquell', 647);
insert into tblurun (ad, fiyat) values ('Blouse / Shirt / Sweater', 240);
insert into tblurun (ad, fiyat) values ('Soap - Mr.clean Floor Soap', 481);
insert into tblurun (ad, fiyat) values ('Wine - Rhine Riesling Wolf Blass', 469);
insert into tblurun (ad, fiyat) values ('Wasabi Paste', 193);
insert into tblurun (ad, fiyat) values ('Tomato Puree', 261);
insert into tblurun (ad, fiyat) values ('Apricots Fresh', 234);
insert into tblurun (ad, fiyat) values ('Mudslide', 602);
insert into tblurun (ad, fiyat) values ('Soup Campbells Turkey Veg.', 261);
insert into tblurun (ad, fiyat) values ('Nut - Almond, Blanched, Ground', 110);
insert into tblurun (ad, fiyat) values ('Sping Loaded Cup Dispenser', 414);
insert into tblurun (ad, fiyat) values ('Hersey Shakes', 54);
insert into tblurun (ad, fiyat) values ('Fork - Plastic', 37);
insert into tblurun (ad, fiyat) values ('Wine - White, Riesling, Henry Of', 533);
insert into tblurun (ad, fiyat) values ('Langers - Cranberry Cocktail', 53);
insert into tblurun (ad, fiyat) values ('Pork - Sausage Casing', 17);
insert into tblurun (ad, fiyat) values ('Hagen Daza - Dk Choocolate', 351);
insert into tblurun (ad, fiyat) values ('Wine - Magnotta - Bel Paese White', 318);
insert into tblurun (ad, fiyat) values ('Graham Cracker Mix', 597);
insert into tblurun (ad, fiyat) values ('Hot Chocolate - Individual', 309);
insert into tblurun (ad, fiyat) values ('The Pop Shoppe - Lime Rickey', 471);
insert into tblurun (ad, fiyat) values ('Tarragon - Fresh', 382);
insert into tblurun (ad, fiyat) values ('Pork - Belly Fresh', 298);
insert into tblurun (ad, fiyat) values ('Water - Green Tea Refresher', 515);
insert into tblurun (ad, fiyat) values ('Ice Cream - Chocolate', 160);
insert into tblurun (ad, fiyat) values ('Foil - Round Foil', 533);
insert into tblurun (ad, fiyat) values ('Honey - Lavender', 41);
insert into tblurun (ad, fiyat) values ('Curry Powder', 360);
insert into tblurun (ad, fiyat) values ('Snapple - Mango Maddness', 435);
insert into tblurun (ad, fiyat) values ('Soup - Campbells, Classic Chix', 55);
insert into tblurun (ad, fiyat) values ('Soup - Boston Clam Chowder', 412);
insert into tblurun (ad, fiyat) values ('Propel Sport Drink', 99);
insert into tblurun (ad, fiyat) values ('Pepper - Orange', 435);
insert into tblurun (ad, fiyat) values ('Cucumber - English', 23);
insert into tblurun (ad, fiyat) values ('Seedlings - Mix, Organic', 342);
insert into tblurun (ad, fiyat) values ('Wine - Riesling Dr. Pauly', 178);
insert into tblurun (ad, fiyat) values ('Juice - Cranberry 284ml', 542);
insert into tblurun (ad, fiyat) values ('Toothpick Frilled', 141);
insert into tblurun (ad, fiyat) values ('Wine - Fino Tio Pepe Gonzalez', 476);
insert into tblurun (ad, fiyat) values ('Soup - Knorr, Classic Can. Chili', 119);
insert into tblurun (ad, fiyat) values ('Tart Shells - Sweet, 3', 401);
insert into tblurun (ad, fiyat) values ('Bread - Raisin Walnut Pull', 57);
insert into tblurun (ad, fiyat) values ('Muffin Mix - Chocolate Chip', 80);
insert into tblurun (ad, fiyat) values ('Salmon - Sockeye Raw', 289);
insert into tblurun (ad, fiyat) values ('Bok Choy - Baby', 431);
insert into tblurun (ad, fiyat) values ('Leeks - Baby, White', 173);
insert into tblurun (ad, fiyat) values ('Pork - Tenderloin, Frozen', 406);
insert into tblurun (ad, fiyat) values ('Garbage Bags - Clear', 376);
insert into tblurun (ad, fiyat) values ('Water, Tap', 626);
insert into tblurun (ad, fiyat) values ('Cheese - Gouda Smoked', 468);
insert into tblurun (ad, fiyat) values ('Shrimp - 21/25, Peel And Deviened', 166);
insert into tblurun (ad, fiyat) values ('Energy Drink - Franks Pineapple', 549);
insert into tblurun (ad, fiyat) values ('Quail - Jumbo Boneless', 315);
insert into tblurun (ad, fiyat) values ('Mushrooms - Honey', 328);
insert into tblurun (ad, fiyat) values ('Syrup - Chocolate', 147);
insert into tblurun (ad, fiyat) values ('Bulgar', 449);
insert into tblurun (ad, fiyat) values ('Nantucket Cranberry Juice', 235);
insert into tblurun (ad, fiyat) values ('Tequila - Sauza Silver', 107);
insert into tblurun (ad, fiyat) values ('Crab - Imitation Flakes', 338);
insert into tblurun (ad, fiyat) values ('Tray - Foam, Square 4 - S', 560);
insert into tblurun (ad, fiyat) values ('Pork - European Side Bacon', 290);
insert into tblurun (ad, fiyat) values ('Chivas Regal - 12 Year Old', 279);
insert into tblurun (ad, fiyat) values ('Trout - Smoked', 532);
insert into tblurun (ad, fiyat) values ('Bread - Calabrese Baguette', 302);
insert into tblurun (ad, fiyat) values ('Coconut - Whole', 569);
insert into tblurun (ad, fiyat) values ('Wine - White, Gewurtzraminer', 367);
insert into tblurun (ad, fiyat) values ('Cloves - Whole', 323);
insert into tblurun (ad, fiyat) values ('Lettuce - Spring Mix', 295);
insert into tblurun (ad, fiyat) values ('Lime Cordial - Roses', 468);
insert into tblurun (ad, fiyat) values ('Coriander - Seed', 41);
insert into tblurun (ad, fiyat) values ('The Pop Shoppe - Cream Soda', 584);
insert into tblurun (ad, fiyat) values ('Bread - White, Sliced', 274);
insert into tblurun (ad, fiyat) values ('Smoked Paprika', 423);
insert into tblurun (ad, fiyat) values ('Tea - Jasmin Green', 44);
insert into tblurun (ad, fiyat) values ('Petite Baguette', 643);
insert into tblurun (ad, fiyat) values ('Cake - Mini Cheesecake', 527);
insert into tblurun (ad, fiyat) values ('Orange - Tangerine', 314);
insert into tblurun (ad, fiyat) values ('Mayonnaise', 632);
insert into tblurun (ad, fiyat) values ('Wine - Remy Pannier Rose', 185);
insert into tblurun (ad, fiyat) values ('Bagel - 12 Grain Preslice', 310);
insert into tblurun (ad, fiyat) values ('Wine - Tio Pepe Sherry Fino', 27);
insert into tblurun (ad, fiyat) values ('Cheese - Colby', 232);
insert into tblurun (ad, fiyat) values ('Pastry - Banana Tea Loaf', 322);
insert into tblurun (ad, fiyat) values ('Anisette - Mcguiness', 238);
insert into tblurun (ad, fiyat) values ('Soup - Campbells Chili Veg', 64);
insert into tblurun (ad, fiyat) values ('Vermouth - Sweet, Cinzano', 495);
insert into tblurun (ad, fiyat) values ('Lettuce - Curly Endive', 173);
insert into tblurun (ad, fiyat) values ('Lambcasing', 381);
insert into tblurun (ad, fiyat) values ('Dasheen', 326);
insert into tblurun (ad, fiyat) values ('Syrup - Monin, Swiss Choclate', 233);
insert into tblurun (ad, fiyat) values ('Liners - Banana, Paper', 185);
insert into tblurun (ad, fiyat) values ('Extract - Lemon', 554);
insert into tblurun (ad, fiyat) values ('Pasta - Penne, Lisce, Dry', 285);
insert into tblurun (ad, fiyat) values ('Bread - Dark Rye, Loaf', 629);
insert into tblurun (ad, fiyat) values ('Beef - Tenderloin', 581);
insert into tblurun (ad, fiyat) values ('Juice - Pineapple, 341 Ml', 505);
insert into tblurun (ad, fiyat) values ('Table Cloth 54x72 White', 52);
insert into tblurun (ad, fiyat) values ('Veal - Ground', 361);
insert into tblurun (ad, fiyat) values ('Nantuket Peach Orange', 580);
insert into tblurun (ad, fiyat) values ('Mushroom - Oyster, Fresh', 373);
insert into tblurun (ad, fiyat) values ('Cake - French Pear Tart', 648);
insert into tblurun (ad, fiyat) values ('Soap - Hand Soap', 507);
insert into tblurun (ad, fiyat) values ('Wine - Chablis 2003 Champs', 117);
insert into tblurun (ad, fiyat) values ('Coffee - Irish Cream', 86);
insert into tblurun (ad, fiyat) values ('Kohlrabi', 478);
insert into tblurun (ad, fiyat) values ('Assorted Desserts', 30);
insert into tblurun (ad, fiyat) values ('Cookies - Fortune', 286);
insert into tblurun (ad, fiyat) values ('Gatorade - Orange', 365);
insert into tblurun (ad, fiyat) values ('Turkey - Whole, Fresh', 245);
insert into tblurun (ad, fiyat) values ('Chocolate - White', 407);
insert into tblurun (ad, fiyat) values ('Rappini - Andy Boy', 566);
insert into tblurun (ad, fiyat) values ('Squid - U - 10 Thailand', 165);
insert into tblurun (ad, fiyat) values ('Tart Shells - Savory, 4', 318);
insert into tblurun (ad, fiyat) values ('Red Currants', 506);
insert into tblurun (ad, fiyat) values ('Lotus Leaves', 414);
insert into tblurun (ad, fiyat) values ('Versatainer Nc - 8288', 540);
insert into tblurun (ad, fiyat) values ('Mustard - Seed', 27);
insert into tblurun (ad, fiyat) values ('Horseradish - Prepared', 27);
insert into tblurun (ad, fiyat) values ('Squash - Acorn', 525);
insert into tblurun (ad, fiyat) values ('Curry Paste - Green Masala', 430);
